"""Bilingual alignment checks for Hindi-English adaptation (Phase 5)."""

from __future__ import annotations

import copy
from typing import Any


def check_bilingual_alignment(
    english: dict[str, Any], bilingual: dict[str, Any]
) -> list[str]:
    """Return alignment errors: IDs/types/order/source fields must match English."""
    errors: list[str] = []
    en_nodes = list(english.get("nodes") or [])
    bi_nodes = list(bilingual.get("nodes") or [])

    if len(en_nodes) != len(bi_nodes):
        errors.append(
            f"node count mismatch: english={len(en_nodes)} bilingual={len(bi_nodes)}"
        )

    en_by_id = {n.get("id"): n for n in en_nodes if n.get("id")}
    bi_by_id = {n.get("id"): n for n in bi_nodes if n.get("id")}

    missing = sorted(set(en_by_id) - set(bi_by_id))
    extra = sorted(set(bi_by_id) - set(en_by_id))
    for nid in missing:
        errors.append(f"missing node id in bilingual: {nid}")
    for nid in extra:
        errors.append(f"extra node id in bilingual: {nid}")

    # Order must follow English order
    en_ids = [n.get("id") for n in en_nodes]
    bi_ids = [n.get("id") for n in bi_nodes]
    if en_ids != bi_ids:
        errors.append("node id order differs from English spine")

    for nid, en in en_by_id.items():
        bi = bi_by_id.get(nid)
        if not bi:
            continue
        for field in (
            "node_type",
            "statement_en",
            "explanation_en",
            "source_status",
            "confidence",
            "order",
            "prev_id",
            "next_id",
        ):
            if en.get(field) != bi.get(field):
                errors.append(f"{nid}.{field} changed during adaptation")
        if list(en.get("source_block_ids") or []) != list(bi.get("source_block_ids") or []):
            errors.append(f"{nid}.source_block_ids changed during adaptation")

    modes = bilingual.get("language_modes") or []
    if "en" not in modes or "hinglish" not in modes:
        errors.append("language_modes must include en and hinglish")

    return errors


def apply_hinglish_fields(
    english: dict[str, Any], adapted: dict[str, Any]
) -> dict[str, Any]:
    """Overlay hinglish fields onto a deep copy of the English spine (safe merge)."""
    out = copy.deepcopy(english)
    adapted_by_id = {
        n.get("id"): n for n in (adapted.get("nodes") or []) if n.get("id")
    }
    for node in out.get("nodes") or []:
        src = adapted_by_id.get(node.get("id"))
        if not src:
            continue
        node["statement_hinglish"] = src.get("statement_hinglish")
        node["explanation_hinglish"] = src.get("explanation_hinglish")
    out["language_modes"] = ["en", "hinglish"]
    return out


def fill_missing_hinglish(spine: dict[str, Any]) -> dict[str, Any]:
    """Ensure hinglish fields exist; leave null only when English is null."""
    out = copy.deepcopy(spine)
    for node in out.get("nodes") or []:
        if node.get("statement_en") and not (node.get("statement_hinglish") or "").strip():
            warnings = list(node.get("warnings") or [])
            if "missing_statement_hinglish" not in warnings:
                warnings.append("missing_statement_hinglish")
            node["warnings"] = warnings
        if node.get("explanation_en") and not (
            node.get("explanation_hinglish") or ""
        ).strip():
            warnings = list(node.get("warnings") or [])
            if "missing_explanation_hinglish" not in warnings:
                warnings.append("missing_explanation_hinglish")
            node["warnings"] = warnings
        if node.get("statement_en") is None:
            node["statement_hinglish"] = None
        if node.get("explanation_en") is None:
            node["explanation_hinglish"] = None
    out["language_modes"] = ["en", "hinglish"]
    return out


def mock_adapt_spine(english: dict[str, Any]) -> dict[str, Any]:
    """Deterministic offline hinglish fill for LLM_MOCK / tests."""
    out = copy.deepcopy(english)
    for node in out.get("nodes") or []:
        stmt = node.get("statement_en")
        expl = node.get("explanation_en")
        if stmt:
            node["statement_hinglish"] = f"Yeh point yeh kehta hai: {stmt}"
        else:
            node["statement_hinglish"] = None
        if expl:
            node["explanation_hinglish"] = f"Simple hinglish explanation: {expl}"
        else:
            node["explanation_hinglish"] = None
        warnings = list(node.get("warnings") or [])
        if "mock_hinglish" not in warnings:
            warnings.append("mock_hinglish")
        node["warnings"] = warnings
    out["language_modes"] = ["en", "hinglish"]
    out["confidence_summary"] = {
        "overall": (out.get("confidence_summary") or {}).get("overall"),
        "notes": "Generated by mock hinglish adaptation (LLM_MOCK=true).",
    }
    return out
